project:
  type: website
execute: 
  freeze: auto
website:
  title: "EAB 703-1002: Biostatistical Methods for the Health Sciences"
  navbar: 
    logo: "UNLV-186.jpg"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - section: "Lectures"
        href: lectures.qmd
        contents:
          - href: lecture1.qmd
            text: Lecture 1- Intro to Biostatistics and R
          - href: lecture2.qmd
            text: Lecture 2- Descriptive Statistics
          - href: lecture3.qmd
            text: Lecture 3- Intro to Probability
          - href: lecture4.qmd
            text: Lecture 4- Probability Distributions
          - href: lecture5.qmd
            text: Lecture 5- Sampling Distributions
          - href: datatransformation.qmd
            text: Supplementary Material - Data Transformation in R
          - href: lecture6.qmd
            text: Lecture 6 - Estimation
          - href: lecture7.qmd
            text: Lecture 7 - Hypothesis Testing
          - href: lecture7-1.qmd
            text: Lecture 7.1 - Tests Involving Variances
          - href: lecture8.qmd
            text: Lecture 8 - Analysis of Variance
          - href: lecture9.qmd
            text: Lecture 9 - Regression and Correlation
      - section: "Problem Sets"
        href: problemsets.qmd
        contents:
          - href: PS1_key.qmd
            text: Problem Set 1 Key
          - href: PS2_key.qmd
            text: Problem Set 2 Key
          - href: PS3_key.qmd
            text: Problem Set 3 Key
          - href: PS4_key.qmd
            text: Problem Set 4 Key
          - href: PS5_key.qmd
            text: Problem Set 5 Key
          - href: PS6_key.qmd
            text: Problem Set 6 Key
          - href: PS7_key.qmd
            text: Problem Set 7 Key
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



